server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.7.0.1:3100/loki/api/v1/push
    batchwait: 10s
    timeout: 30s

scrape_configs:
  - job_name: 'docker-logs'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s

    pipeline_stages:
      - docker: {}

    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container_name
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
      - source_labels: [__meta_docker_container_image]
        target_label: image_name
      - replacement: 'stage-droplet'
        target_label: host