name: Deploy Monitoring Stack

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Stop and remove old containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_SSH_KEY }}
          script: |
            docker stop prometheus grafana alertmanager || true
            docker rm prometheus grafana alertmanager || true

      - name: Deploy new containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker pull prom/prometheus
            docker pull grafana/grafana
            docker pull prom/alertmanager
            docker run -d -v /var/lib/prometheus:/prometheus --net ngdem -p 9090:9090 --name prometheus prom/prometheus
            docker run -d -v /var/lib/grafana:/var/lib/grafana --net ngdem -p 3000:3000 --name grafana grafana/grafana
            docker run -d -v /var/lib/alertmanager:/alertmanager --net ngdem -p 9093:9093 --name alertmanager prom/alertmanager
            
            # WireGuard
