name: Deploy Prometheus

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare Prometheus directory and remove old container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            if [ ! -d /home/${{ secrets.VPS_USERNAME }}/prometheus ]; then
              mkdir -p /home/${{ secrets.VPS_USERNAME }}/prometheus
            else
              rm -rf /home/${{ secrets.VPS_USERNAME }}/prometheus/*
            fi
            docker stop prometheus || true
            docker rm prometheus || true

      - name: Copy Prometheus configuration
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "./prometheus/prometheus.yml"
          target: "/home/${{ secrets.VPS_USERNAME }}/prometheus/prometheus.yml"

      - name: Deploy Prometheus container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker pull prom/prometheus
            docker run -d -v /home/${{ secrets.VPS_USERNAME }}/prometheus:/prometheus -v /home/${{ secrets.VPS_USERNAME }}/prometheus.yml:/etc/prometheus/prometheus.yml --name prometheus --net ngdem -p 9090:9090 prom/prometheus

      - name: Health check Prometheus
        run: curl -f http://${{ secrets.VPS_HOST }}:9090/-/healthy || exit 1
