name: Deploy Loki on the monitoring-vps

on:
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy loki configuration
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "./loki-config.yml"
          target: "/home/${{ secrets.VPS_USERNAME }}/loki/"

      - name: Remove old container and deploy loki container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker stop loki || true
            docker rm loki || true            
            docker pull grafana/loki:latest
            docker run -d --restart=unless-stopped --name loki --net ngdem -p 3100:3100 \
                -v /home/${{ secrets.VPS_USERNAME }}/loki/loki-config.yml:/etc/loki/loki-config.yml \
                -v /var/lib/loki/chunks:/loki/chunks -v /var/lib/loki/rules:/loki/rules \
                grafana/loki:latest -config.file=/etc/loki/loki-config.yml
  
  healthcheck:
    needs: [deploy]   
    runs-on: ubuntu-latest   
    outputs:   
      id: healthcheck_output   
    steps:   
      - name: Run Healthcheck
        id: healthcheck_status 
        uses: appleboy/ssh-action@master   
        with:   
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}   
          script: |
            retries=3
            delay_seconds=20

            for attempt in $(seq "$retries"); do
            http_status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3100/ready)
              
              if [ "$http_status" -eq 200 ]; then
                echo "The service has been successfully raised"
                echo "status=success" >> "$GITHUB_ENV"
                exit 0
              else
                echo "Error: Service not available (attempt $attempt/$retries)"
              fi

              if [ "$attempt" -lt "$retries" ]; then
                sleep "$delay_seconds"
              fi
            done

            echo "Failed to start new container."
            echo "status=failure" >> "$GITHUB_ENV"
            exit 1