name: Test copy on the DO droplet

on:
  workflow_dispatch:

jobs:
  deploy:
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
           
      - name: Copy promtail configuration
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST_STAGE }}
          username: ${{ secrets.VPS_USERNAME_STAGE }}
          password: ${{ secrets.VPS_PASSWORD_STAGE }}
          source: "./stage-promtail-config.yml"
          target: "/home/${{ secrets.VPS_USERNAME_STAGE }}/promtail/"
